#!/usr/bin/env python3
"""
update-gallery.py
Scans your photo folders and writes gallery-photos.js.
Run this once whenever you add or remove photos.

Folder structure:
  images/paradise/   <- all Paradise Villa photos (any filenames)
  images/casanova/   <- all Casa Nova photos (any filenames)

OR flat images/ folder with p/c prefixes:
  images/p1.jpg, p2.jpg ...  (paradise)
  images/c1.jpg, c2.jpg ...  (casa nova)
"""
import os

EXTS = {'.jpg', '.jpeg', '.png', '.webp', '.gif'}

def scan(folder):
    if not os.path.isdir(folder):
        return []
    return sorted(f for f in os.listdir(folder)
                  if os.path.splitext(f)[1].lower() in EXTS)

print("\n=== Luce d\'Istria Gallery Updater ===\n")

# Paradise Villa
if os.path.isdir('images/paradise') and scan('images/paradise'):
    paradise = scan('images/paradise')
    print(f"Paradise Villa : {len(paradise)} photos from images/paradise/")
else:
    paradise = [f for f in scan('images') if f.lower().startswith('p')]
    print(f"Paradise Villa : {len(paradise)} photos from images/ (prefix p)")

# Villa Casa Nova
if os.path.isdir('images/casanova') and scan('images/casanova'):
    casanova = scan('images/casanova')
    print(f"Villa Casa Nova: {len(casanova)} photos from images/casanova/")
else:
    casanova = [f for f in scan('images') if f.lower().startswith('c')]
    print(f"Villa Casa Nova: {len(casanova)} photos from images/ (prefix c)")

# Write gallery-photos.js
def arr(photos):
    if not photos:
        return "[]"
    return "[\n  '" + "',\n  '".join(photos) + "'\n]"

js = f"""// gallery-photos.js — auto-generated by update-gallery.py
// Do not edit manually. Run: python update-gallery.py

const PARADISE_PHOTOS = {arr(paradise)};

const CASANOVA_PHOTOS = {arr(casanova)};
"""

with open('gallery-photos.js', 'w', encoding='utf-8') as f:
    f.write(js)

print("\n✅ gallery-photos.js updated — refresh your browser.")
print("   (You do NOT need to re-download the HTML files.)")
